data_dir: /content/data
processed_dir: /content/processed_data
output_dir: /content/drive/MyDrive/Projects/DSS/lstmFeature8hourstransformerCNN/output
model_dir: /content/drive/MyDrive/Projects/DSS/lstmFeature8hourstransformerCNN/output/train
sub_dir: /content/