data_dir: /content/data
processed_dir: /content/processed_data
output_dir: /content/drive/MyDrive/Projects/DSS/lstmFeature12Hours/output
model_dir: /content/drive/MyDrive/Projects/DSS/lstmFeature12Hours/train
sub_dir: /content/